### ISSUE TITLE
Segfault when trying run ardrone_driver

### ISSUE THREAD

**Issue by pratiksen** [AutonomyLab/ardrone_autonomy#64] opened 2013-05-11 09:01 UTC
Hello,
...After getting a successful Rosmake of the package, when I tried to run the driver it emits a segfault during the initialization process. I'm not sure what exactly is going and would really appreciate some help.

Thanks,

Sen

Ubuntu 12.10
Ros Groovy

heres the output...

user$~ rosrun ardrone_autonomy ardrone_driver
Wait authentification
Wait authentification
Wait authentification
===================+> 192.168.1.1
[ INFO] [1368262008.957043787]: Root Frame is: 0
[ INFO] [1368262008.958842421]: No values found for `~cov/imu_la` in parameters, set all to zero.
[ INFO] [1368262008.960211071]: No values found for `~cov/imu_av` in parameters, set all to zero.
[ INFO] [1368262008.961594793]: No values found for `~cov/imu_or` in parameters, set all to zero.
Deleting Profile -cea48d22
Deleting Application -e182b69b
Input device Teleop added
Starting thread video_stage
Starting thread video_recorder

video stage thread initialisation

Starting thread update_ros
Video multisocket : init 2 sockets
Video multisocket : connecting socket 0 on port 5555 UDP
Video recorder thread initialisation
Video multisocket : connecting socket 1 on port 5555 TCP
Set IP_TOS ok
Starting thread navdata_update
Thread `update_ros` started 
 Starting thread ardrone_control
Thread navdata_update in progress...
Start thread thread_academy_download 
Academy download stage resumed
PA : MEMORY SPACE ALLOWED : 40 MB
Start thread thread_academy
Start thread thread_academy_upload
Segmentation fault (core dumped)

**Comment by mani-monaj** [comment] 2013-11-15 00:35
possible duplicate of #69

**Closed as completed by mani-monaj** 2013-11-15 00:35 UTC
