### ISSUE TITLE
hydro runtime issues

### ISSUE THREAD

**Issue by x75** [AutonomyLab/ardrone_autonomy#94] opened 2014-03-04 17:08 UTC
hi,

been doing some testing today with catkin branch of ardrone_autonomy since i'd like to run it with hydro.
# 

on a debian/unstable system:
rosrun ardrone_autonomy ardrone_driver results in segfault from ardrone_driver.cpp line 840:
   vp_com_wifi_config_t _config = (vp_com_wifi_config_t_)wifi_config();

i assume this originates directly from the SDK but so far i couldn't figure out more details.
# 

on an ubuntu 13.04 system i get a somewhat more involved output:

$ rosrun ardrone_autonomy ardrone_driver 
Wait authentification
Wait authentification
Wait authentification
===================+> 192.168.1.1
Getting AR.Drone version ...
[ERROR] [1393946915.567875336]: [registerPublisher] Failed to contact master at [localhost:11311].  Retry
[ INFO] [1393946924.429917023]: Connected to master at [localhost:11311]
[ INFO] [1393946925.128314469]: Root Frame is: 0
[ INFO] [1393946925.130801957]: No values found for `~cov/imu_la` in parameters, set all to zero.
[ INFO] [1393946925.132617406]: No values found for `~cov/imu_av` in parameters, set all to zero.
[ INFO] [1393946925.134340826]: No values found for `~cov/imu_or` in parameters, set all to zero.
Deleting Profile -cea48d22
Deleting Application -e182b69b
Input device Teleop added
Starting thread video_stage
Starting thread video_recorder
Starting thread update_ros
Failed to open AT
Starting thread navdata_update
Starting thread ardrone_control
PA : MEMORY SPACE ALLOWED : 40 MB
Thread `update_ros` started 
 Video recorder thread initialisation
VP_Com : Failed to open socket for navdata
Start thread thread_academy_download 
Academy download stage resumed
Start thread thread_academy_upload
Start thread thread_academy

video stage thread initialisation

Video multisocket : init 2 sockets
Video multisocket : connecting socket 0 on port 5555 UDP
- Connection failed
  Video multisocket : connecting socket 1 on port 5555 TCP
  Academy download stage paused
  Segmentation fault (core dumped)
# 

on an ubuntu 12.04 LTS everything works! :)

**Comment by mani-monaj** [comment] 2014-03-06 23:27
Thanks for reporting this. Could you also test the `hydro-devel` branch?

**Comment by x75** [comment] 2014-03-11 09:03
Thanks for getting back.

Initially i also tested hydro-devel, just checked again, on the debian/unstable i get the same segfault.

In the meantime i built the driver on yet another ubuntu 13.04 and this worked fine, been flying with that already with no issues.

**Comment by mani-monaj** [comment] 2014-03-16 00:34
@x75 I have not tested the _hydro-devel_ branch on 13.04 or 13.10 yet. I will do that. However, as of two days ago the pre-built binaries of the driver for _hydro_ is available via ROS repositories. You may want to install the driver using `apt-get` and check if it solves the problem.

**Comment by mani-monaj** [comment] 2015-01-10 22:01
Since it is an unconfirmed bug, I will close this. If the problem still exists, please re-open the issue with more details.

**Closed as completed by mani-monaj** 2015-01-10 22:01 UTC
Labels: bug, unconfirmed

**Comment by olivierdm** [comment] 2015-02-23 22:24
Running Ubuntu 14.04 with ROS Indigo. I experience the same problem. Debugger also stops at this line: vp_com_wifi_config_t _config = reinterpret_cast<vp_com_wifi_config_t_>(wifi_config());
The same configuration works in Virtual Box on the same host machine.

**Comment by olivierdm** [comment] 2015-02-23 23:45
EDIT: I had OpenVPN running in the background. This caused the Segmentation fault. Stopping the VPN solved my problem.
