### ISSUE TITLE
Choppy stream from Cameras

### ISSUE THREAD

**Issue by devagl** [AutonomyLab/ardrone_autonomy#19] opened 2012-10-22 07:10 UTC
I'm trying to implement autonomous landing using the bottom camera, and this application heavily relies on a steady, constant camera frame rate. The current frame rate can vary from anywhere between 0.1-0.12 secs, and sometimes when it freezes, there is no image for up to 2 secs altogether. although I don't need the front camera now, the stream from it seems to be fairly constant, but the bottom camera gives a very choppy stream more often than not. 

I've tested this with my freeflight app of course, and it seems fine then.

This feed is usually accompanied by messages like "Timeout when reading navdatas - resending a navdata request on port 5554", "Decoding failed for I frame", "Decoding Failed for P frame". What can i do to improve the link between the computer and the drone? I'm guessing that's the cause for this, and not a bug in the driver?

**Comment by maxpfingsthorn** [comment] 2013-01-24 09:15
I have the same problem, though for both the front and bottom cameras. Any comments would be much appreciated. Buying new hardware (big antenna for my wifi) wouldn't solve this issue, as it works fine on my iPhone/iPad, just like mentioned above.

**Comment by mani-monaj** [comment] 2015-01-10 21:31
Any updates on this?

**Comment by devagl** [comment] 2015-01-10 21:46
This is definitely not a scientifically sound answer, but once I moved to a bigger, secluded room where there was no one around me using a computer (lack of other interfering WiFi signals), this issue became significantly better for me. 

This still does not tell us why it works well with the iPhones though ...

**Comment by mani-monaj** [comment] 2015-01-10 21:51
@devmax That's very interesting. I've experienced similar issues with Wifi interference. Have you ever tried using a better (in terms of Linux compatibility) wireless interface on your PC?

**Comment by devagl** [comment] 2015-01-10 23:05
Unfortunately, I haven't worked with the drone for 2 years now but that does sound like an interesting experiment! 

—Dev

**Comment by mani-monaj** [comment] 2016-04-14 20:25
Since the issue is not confirmed, I will close it until any new detail is available.

**Closed as completed by mani-monaj** 2016-04-14 20:25 UTC
Labels: bug, enhancement, unconfirmed
